#!/usr/bin/env python3
"""
smoke_test.py — Automated inter-region connectivity smoke tests.

Reads instances.json (generated by deploy.py) and verifies that each bastion
can reach private hosts in every other region via ping over SSH.

Usage
-----
    python scripts/smoke_test.py [options]

    --instances PATH      Path to instances.json (default: instances.json in repo root)
    --key-dir  DIR        Directory containing SSH private keys (default: ssh-keys/ in repo root)
    --timeout  SECONDS    SSH/ping timeout in seconds (default: 30)
    --dry-run             Print what would be tested without running SSH commands
    --regions  r1,r2,...  Only test paths involving these region short-names (e.g. euw2,use1)

instances.json schema (as written by deploy.py --json)
------------------------------------------------------
The file is a JSON object keyed by cell path, e.g.:

    {
      "envs/dev/euw2/cell1000": {
        "bastions": {
          "bastion-euw2-dev-pub-0-cell1000": "35.178.244.94",
          ...
        },
        "private_hosts": {
          "private-euw2-dev-priv-0-cell1000": "10.1.0.148",
          ...
        }
      },
      ...
    }

Key files are expected at: <key-dir>/<region>-<env>.pem
  e.g. ssh-keys/euw2-dev.pem

Exit codes
----------
    0  All tests passed (or --dry-run)
    1  One or more tests failed
    2  Usage or configuration error
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Data loading and pair building
# ---------------------------------------------------------------------------


def load_instances(path: str) -> list[dict]:
    """
    Load instances.json and return a flat list of cell descriptors.

    Each descriptor is a dict with keys:
        cell_path   str  e.g. "envs/dev/euw2/cell1000"
        env         str  e.g. "dev"
        region      str  e.g. "euw2"
        cell        str  e.g. "cell1000"
        bastion_ip  str  public IP of the first bastion in the cell
        private_ip  str  private IP of the first private host in the cell
        key_name    str  key filename stem, e.g. "euw2-dev"

    Cells that lack either bastions or private_hosts are silently skipped.

    Raises
    ------
    FileNotFoundError
        If *path* does not exist.
    ValueError
        If the file is not valid JSON or does not match the expected schema.
    """
    instances_path = Path(path)
    if not instances_path.exists():
        raise FileNotFoundError(
            f"instances.json not found at '{path}'. "
            "Run 'python scripts/deploy.py --json' to generate it."
        )

    try:
        raw = json.loads(instances_path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(f"Failed to parse '{path}' as JSON: {exc}") from exc

    if not isinstance(raw, dict):
        raise ValueError(
            f"Expected instances.json to be a JSON object (dict), got {type(raw).__name__}."
        )

    cells: list[dict] = []
    for cell_path, cell_data in raw.items():
        # Parse path components: envs/<env>/<region>/<cell>
        parts = cell_path.strip("/").split("/")
        if len(parts) < 4 or parts[0] != "envs":
            # Skip unexpected keys silently
            continue

        _, env, region, cell = parts[0], parts[1], parts[2], parts[3]

        if not isinstance(cell_data, dict):
            continue

        bastions: dict = cell_data.get("bastions", {})
        private_hosts: dict = cell_data.get("private_hosts", {})

        if not bastions or not private_hosts:
            continue

        # Use the lexicographically first bastion / private host for consistency
        bastion_ip = next(v for _, v in sorted(bastions.items()))
        private_ip = next(v for _, v in sorted(private_hosts.items()))

        cells.append(
            {
                "cell_path": cell_path,
                "env": env,
                "region": region,
                "cell": cell,
                "bastion_ip": bastion_ip,
                "private_ip": private_ip,
                "key_name": f"{region}-{env}",
            }
        )

    return cells


def build_test_pairs(
    instances: list[dict],
    regions: Optional[list[str]],
) -> list[tuple[dict, dict]]:
    """
    Return all ordered (src, dst) pairs where src and dst are in different regions.

    If *regions* is a non-empty list, only pairs where *both* src.region and
    dst.region appear in *regions* are included.  Pass ``None`` or ``[]`` to
    include all regions.

    Parameters
    ----------
    instances:
        Flat list of cell descriptors as returned by :func:`load_instances`.
    regions:
        Optional allowlist of region short-names.

    Returns
    -------
    list[tuple[dict, dict]]
        Ordered list of (src_cell, dst_cell) descriptor pairs.
    """
    if regions:
        region_set = set(regions)
        filtered = [i for i in instances if i["region"] in region_set]
    else:
        filtered = instances

    pairs: list[tuple[dict, dict]] = []
    for src in filtered:
        for dst in filtered:
            if src["region"] != dst["region"]:
                pairs.append((src, dst))

    return pairs


# ---------------------------------------------------------------------------
# Test execution
# ---------------------------------------------------------------------------


def run_ping_test(
    src: dict,
    dst: dict,
    key_dir: str,
    timeout: int,
) -> dict:
    """
    SSH to *src*'s bastion and run ``ping -c 3`` to *dst*'s private IP.

    Parameters
    ----------
    src:
        Source cell descriptor (must contain bastion_ip, key_name, region, cell).
    dst:
        Destination cell descriptor (must contain private_ip, region, cell).
    key_dir:
        Directory containing SSH private key files named ``<key_name>.pem``.
    timeout:
        Seconds before the subprocess is killed.

    Returns
    -------
    dict with keys:
        src       str   "<region>/<cell>"
        dst       str   "<region>/<cell>"
        status    str   "PASS" | "FAIL" | "ERROR"
        latency   str   average round-trip time string, or "" if unavailable
        output    str   combined stdout/stderr from the SSH command
    """
    key_path = Path(key_dir) / f"{src['key_name']}.pem"
    src_label = f"{src['region']}/{src['cell']}"
    dst_label = f"{dst['region']}/{dst['cell']}"

    cmd = [
        "ssh",
        "-i", str(key_path),
        "-o", "StrictHostKeyChecking=no",
        "-o", "BatchMode=yes",
        "-o", "ConnectTimeout=10",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "LogLevel=ERROR",
        f"ec2-user@{src['bastion_ip']}",
        f"ping -c 3 -W 5 {dst['private_ip']}",
    ]

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        output = (proc.stdout + proc.stderr).strip()
        status = "PASS" if proc.returncode == 0 else "FAIL"
        latency = _parse_ping_latency(proc.stdout)
    except subprocess.TimeoutExpired:
        status = "ERROR"
        latency = ""
        output = f"Timed out after {timeout}s"
    except FileNotFoundError:
        status = "ERROR"
        latency = ""
        output = "ssh binary not found — is OpenSSH installed?"
    except OSError as exc:
        status = "ERROR"
        latency = ""
        output = f"OS error: {exc}"

    return {
        "src": src_label,
        "dst": dst_label,
        "status": status,
        "latency": latency,
        "output": output,
    }


def _parse_ping_latency(ping_output: str) -> str:
    """
    Extract the average RTT from ping output, e.g. ``"12.345 ms"``.

    Handles both Linux (``rtt min/avg/max/mdev``) and macOS
    (``round-trip min/avg/max/stddev``) ping summary lines.

    Returns an empty string if the pattern is not found.
    """
    # Linux:  rtt min/avg/max/mdev = 1.234/5.678/9.012/0.123 ms
    # macOS:  round-trip min/avg/max/stddev = 1.234/5.678/9.012/0.123 ms
    match = re.search(
        r"(?:rtt|round-trip)\s+min/avg/max/\S+\s*=\s*[\d.]+/([\d.]+)/[\d.]+",
        ping_output,
    )
    if match:
        return f"{match.group(1)} ms"
    return ""


# ---------------------------------------------------------------------------
# Result rendering
# ---------------------------------------------------------------------------


def render_results(results: list[dict]) -> str:
    """
    Render a plain-text table of smoke-test results.

    Parameters
    ----------
    results:
        List of result dicts as returned by :func:`run_ping_test` (or the
        dry-run equivalent).

    Returns
    -------
    str
        A formatted table string ready to be printed to stdout.
    """
    if not results:
        return "No tests to display."

    # Column headers
    col_src = "SRC (region/cell)"
    col_dst = "DST (region/cell)"
    col_status = "STATUS"
    col_latency = "LATENCY"

    # Compute column widths
    w_src = max(len(col_src), *(len(r["src"]) for r in results))
    w_dst = max(len(col_dst), *(len(r["dst"]) for r in results))
    w_status = max(len(col_status), *(len(r["status"]) for r in results))
    w_latency = max(len(col_latency), *(len(r.get("latency", "")) for r in results))

    sep = (
        "+-"
        + "-" * w_src
        + "-+-"
        + "-" * w_dst
        + "-+-"
        + "-" * w_status
        + "-+-"
        + "-" * w_latency
        + "-+"
    )
    header = (
        "| "
        + col_src.ljust(w_src)
        + " | "
        + col_dst.ljust(w_dst)
        + " | "
        + col_status.ljust(w_status)
        + " | "
        + col_latency.ljust(w_latency)
        + " |"
    )

    lines: list[str] = [sep, header, sep]
    for r in results:
        row = (
            "| "
            + r["src"].ljust(w_src)
            + " | "
            + r["dst"].ljust(w_dst)
            + " | "
            + r["status"].ljust(w_status)
            + " | "
            + r.get("latency", "").ljust(w_latency)
            + " |"
        )
        lines.append(row)
    lines.append(sep)

    # Summary line
    total = len(results)
    passed = sum(1 for r in results if r["status"] == "PASS")
    failed = sum(1 for r in results if r["status"] == "FAIL")
    errors = sum(1 for r in results if r["status"] == "ERROR")
    lines.append(
        f"\nTotal: {total}  Passed: {passed}  Failed: {failed}  Errors: {errors}"
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="smoke_test.py",
        description=(
            "Automated inter-region connectivity smoke tests. "
            "SSHes to each bastion and pings private hosts in other regions."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/smoke_test.py\n"
            "  python scripts/smoke_test.py --instances instances.json --key-dir ssh-keys/\n"
            "  python scripts/smoke_test.py --regions euw2,use1 --dry-run\n"
            "  python scripts/smoke_test.py --timeout 60"
        ),
    )
    parser.add_argument(
        "--instances",
        default=str(_REPO_ROOT / "instances.json"),
        metavar="PATH",
        help="Path to instances.json (default: instances.json in repo root)",
    )
    parser.add_argument(
        "--key-dir",
        default=str(_REPO_ROOT / "ssh-keys"),
        metavar="DIR",
        help="Directory containing SSH private key files (default: ssh-keys/ in repo root)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=30,
        metavar="SECONDS",
        help="SSH/ping timeout in seconds (default: 30)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be tested without running SSH commands",
    )
    parser.add_argument(
        "--regions",
        default=None,
        metavar="r1,r2,...",
        help="Comma-separated region short-names to filter tests (e.g. euw2,use1)",
    )
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    """
    Entry point for the smoke test CLI.

    Parameters
    ----------
    argv:
        Argument list (defaults to sys.argv[1:] when None).

    Returns
    -------
    int
        0 if all tests passed (or --dry-run), 1 if any test failed, 2 on usage error.
    """
    args = _parse_args(argv)

    # Parse optional regions filter
    regions: Optional[list[str]] = None
    if args.regions:
        regions = [r.strip() for r in args.regions.split(",") if r.strip()]

    # Load instances
    try:
        instances = load_instances(args.instances)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if not instances:
        print("ERROR: No usable cells found in instances.json.", file=sys.stderr)
        return 2

    # Build test pairs
    pairs = build_test_pairs(instances, regions)

    if not pairs:
        region_msg = f" for regions {regions}" if regions else ""
        print(f"No cross-region test pairs found{region_msg}.", file=sys.stderr)
        return 2

    print(f"Found {len(instances)} cell(s). Running {len(pairs)} cross-region test(s).")
    if args.dry_run:
        print("DRY-RUN mode — SSH commands will not be executed.\n")

    # Validate key directory exists (warn but continue; individual tests will surface errors)
    key_dir_path = Path(args.key_dir)
    if not key_dir_path.is_dir():
        print(
            f"WARNING: key-dir '{args.key_dir}' does not exist. "
            "SSH tests will fail unless keys are found elsewhere.",
            file=sys.stderr,
        )

    # Run tests
    results: list[dict] = []
    for src, dst in pairs:
        src_label = f"{src['region']}/{src['cell']}"
        dst_label = f"{dst['region']}/{dst['cell']}"
        key_file = key_dir_path / f"{src['key_name']}.pem"

        if args.dry_run:
            print(
                f"  [DRY-RUN] Would SSH to {src['bastion_ip']} "
                f"(key: {key_file}) and ping {dst['private_ip']}"
                f"  [{src_label} -> {dst_label}]"
            )
            results.append(
                {
                    "src": src_label,
                    "dst": dst_label,
                    "status": "DRY-RUN",
                    "latency": "",
                    "output": "",
                }
            )
        else:
            print(f"  Testing {src_label} -> {dst_label} ...", end=" ", flush=True)
            result = run_ping_test(src, dst, args.key_dir, args.timeout)
            latency_str = f" ({result['latency']})" if result["latency"] else ""
            print(f"{result['status']}{latency_str}")

            # Print SSH/ping output on failure for diagnosis
            if result["status"] != "PASS" and result["output"]:
                for line in result["output"].splitlines():
                    print(f"    | {line}")

            results.append(result)

    # Render summary table
    print()
    print(render_results(results))

    if args.dry_run:
        return 0

    any_failed = any(r["status"] != "PASS" for r in results)
    return 1 if any_failed else 0


if __name__ == "__main__":
    sys.exit(main())
